"""first migration

Revision ID: 2725dc0c553d
Revises: 40936c8c0813
Create Date: 2023-04-12 14:45:05.106054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2725dc0c553d'
down_revision = '40936c8c0813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
