"""first migration

Revision ID: 40936c8c0813
Revises: 0159d26ea545
Create Date: 2023-04-12 14:42:19.542178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40936c8c0813'
down_revision = '0159d26ea545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
