"""first migration

Revision ID: a6ac79d5b4a6
Revises: f7f0af0ce005
Create Date: 2023-04-16 15:42:31.775115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac79d5b4a6'
down_revision = 'f7f0af0ce005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
